# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4bb1a6be0babe59c2b7b418788c3525cc1571b6203025ad14cfc1901aed7a2c58f39be248385ff74c45a1ec232bdc297b5f1a0b8b799a48fe45b1c2c26e3ae2d

test:
  secret_key_base: 45e362fdd5210c05fb8ed01d41e57d57e41d65af3f434f628dddb7d7078bfa494bbd3e0536cf166c552f3711c9c359f7d1a07621fbed6b76c8c0cce9c79e7683

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
